# Generated by Django 4.0.4 on 2022-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
