# Generated by Django 4.0.4 on 2022-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.IntegerField()),
                ('Strategy', models.IntegerField()),
                ('Aesthetics', models.IntegerField()),
                ('Competition', models.IntegerField()),
                ('Fellowship', models.IntegerField()),
                ('Challenge', models.IntegerField()),
                ('Discovery', models.IntegerField()),
                ('Completion', models.IntegerField()),
                ('Expression', models.IntegerField()),
                ('Story', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='characteristic',
            field=models.CharField(choices=[('---', '---'), ('action', 'action'), ('strategy', 'strategy'), ('aesthetics', 'aesthetics'), ('competition', 'competition'), ('fellowship', 'fellowship'), ('challenge', 'challenge'), ('discovery', 'discovery'), ('completion', 'completion'), ('expression', 'expression'), ('story', 'story')], default=0, max_length=22),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.CharField(max_length=50),
        ),
    ]
