# Generated by Django 4.0.4 on 2022-06-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_characteristic_answer_characteristic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
