# Generated by Django 4.0.4 on 2022-06-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_delete_characteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='question',
            name='characteristic',
            field=models.CharField(choices=[('---', '---'), ('action', 'action'), ('strategy', 'strategy'), ('aesthetics', 'aesthetics'), ('competition', 'competition'), ('fellowship', 'fellowship'), ('challenge', 'challenge'), ('discovery', 'discovery'), ('completion', 'completion'), ('expression', 'expression'), ('story', 'story')], default=0, max_length=22),
        ),
    ]
