# Generated by Django 4.0.4 on 2022-06-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_gameslist_number_of_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GamesList',
        ),
    ]
